import ollama


from config import OLLAMA_MODEL


SYSTEM_PROMPT = (
    "You are an expert Student Success Coach.\n"
    "Always return ONLY valid JSON.\n"
    "Do NOT include markdown.\n"
    "Do NOT include explanations.\n"
    "Do NOT include extra text."
)


def call_ollama(prompt: str) -> str:
    """
    Sends the prompt to Ollama and returns a validated JSON response.

    Args:
        prompt (str): Complete prompt generated by prompt_builder.py.

    Returns:
        str: Raw JSON response returned by Ollama.

    Raises:
        RuntimeError: If communication with Ollama fails or an invalid response is received.
    """

    try:
        response = ollama.chat(
            model=OLLAMA_MODEL,
            format="json",
            options={
                "temperature": 0,

            },
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )

    except Exception as e:
        raise RuntimeError(f"Failed to communicate with Ollama: {e}")

    try:
        response_text = response["message"]["content"]
    except KeyError:
        raise RuntimeError("Unexpected response format returned by Ollama.")

    return response_text